version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Specify the version of Python you're using
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # Install Python dependencies

  pre_build:
    commands:
      - echo Setting environment variables for production...
      - export DJANGO_SETTINGS_MODULE=url_shortener.settings  # Point to the production settings
      # You can add any additional environment variable settings here

  build:
    commands:
 # Apply database migrations
      - echo Collecting static files...
      - python3 manage.py collectstatic --noinput  # Collect static files for production
    

artifacts:
  files:
    - '**/*'  # Include all files in the build artifact, adjust as needed
