version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Specify the version of Python you're using
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # Install Python dependencies

  build:
    commands:
      - echo Starting the application...
      - python3 manage.py runserver  # Start the application (you can change this if you need to)

artifacts:
  files:
    - '**/*'  # Include all files in the build artifact, change if needed
